### ISSUE TITLE
Fix the arm build

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/net.poedit.Poedit#1]
Currently, the arm build doesn't work due to an issue with cpprestsdk

**Comment by Eonfge** [comment]
Fixed with latest merge request:
https://github.com/flathub/net.poedit.Poedit/pull/27

**Comment by hfiguiere** [comment]
We no longer support that platform anyway since freedesktop-sdk 20.08 (or GNOME 3.38 and up)

**Comment by Eonfge** [comment]
wahahah, well, problem solved itself :sunglasses:
