### ISSUE TITLE
The GNOME 3.36 runtime is no longer supported.

### ISSUE THREAD

**Issue by Latesil** [flathub/net.poedit.Poedit#24]
When I try to update Poedit it says: `The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.`.

**Comment by bilelmoussaoui** [comment]
see #23

**Comment by Eonfge** [comment]
Fixed with latest merge request:
https://github.com/flathub/net.poedit.Poedit/pull/27
