### ISSUE TITLE
Release 2.4.3 not coming through

### ISSUE THREAD

**Issue by Eonfge** [flathub/net.poedit.Poedit#28]
@bilelmoussaoui i think something has gone wrong.

The current version of Poedit is still 2.4.2 using the 3.36 runtime
https://flathub.org/apps/details/net.poedit.Poedit

I don't see anything on the build server, so I think you'll have to take a look.

**Comment by bilelmoussaoui** [comment]
I have triggered a new build, let's see how that goes

**Comment by hfiguiere** [comment]
build failed because the boost download URL is 404.

They all changed. See https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html
