### ISSUE TITLE
Hosted rev 6 months old; update to 2.1.1

### ISSUE THREAD

**Issue by sanecito** [flathub/net.poedit.Poedit#3]
Current rev hosted is 2.0.6 which is roughly 6 months old compared to current actual release (2.1.1). Please update to the current release @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
Will update and do some tests today

**Comment by nedrichards** [comment]
Am looking at this as well @bilelmoussaoui I should have a PR up shortly for further testing if you want. We should look at getting some flathub requirements like OARS into the upstream appdata as well.

**Comment by bilelmoussaoui** [comment]
@nedrichards Pushed a new AppData update to upstream here https://github.com/vslavik/poedit/pull/514
What do you think of that?

**Comment by nedrichards** [comment]
looks good!

**Comment by cho2** [comment]
When will update to 2.2 (https://github.com/vslavik/poedit/releases/tag/v2.2-oss) ?

**Comment by cho2** [comment]
> When will update to 2.2 (https://github.com/vslavik/poedit/releases/tag/v2.2-oss) ?

Instead of ask, i try to make pull request https://github.com/flathub/net.poedit.Poedit/pull/6

**Comment by AdsonCicilioti** [comment]
Snapcraft is the pakage manager oficial

**Comment by bilelmoussaoui** [comment]
@AdsonCicilioti How is related to help or update this package? This is not a forum, please keep the issues related only to what the user is reporting.

**Comment by bilelmoussaoui** [comment]
Sorry guys for the delay. I was a bit busy and totally forgot about this one. The latest Poedit version should be on Flathub pretty soon.
