### ISSUE TITLE
Error: assert ""IsOk()"" failed in GetWidth(): invalid bitmap

### ISSUE THREAD

**Issue by sabriunal** [flathub/net.poedit.Poedit#37]
Hi, I installed poedit from Flathub via flatpak

`flatpak install flathub net.poedit.Poedit`

When I run it, it has two errors

`flatpak run net.poedit.Poedit`

```
Gtk-Message: 21:07:29.251: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:07:29.252: Failed to load module "canberra-gtk-module"
Debug: Failed to connect to session manager: None of the authentication protocols specified are supported
./src/gtk/bitmap.cpp(937): assert ""IsOk()"" failed in GetWidth(): invalid bitmap
Debug: window wxTextCtrl(0x55912da24630) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x55912da24630) lost focus even though it didn't have it


(net.poedit.Poedit:2): Gtk-CRITICAL **: 21:07:38.784: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
(net.poedit.Poedit:2): Gtk-CRITICAL **: 21:07:38.820: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

Debug: cannot read address information for stack frame #0
./src/gtk/bitmap.cpp(767): assert ""IsOk()"" failed in ConvertToImage(): invalid bitmap
./src/common/image.cpp(438): assert ""IsOk()"" failed in Scale(): invalid image
./src/gtk/bitmap.cpp(593): assert ""image.IsOk()"" failed in wxBitmap(): invalid image

(net.poedit.Poedit:2): Gtk-CRITICAL **: 21:07:50.489: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Debug: window wxTextCtrl(0x55912da24630) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x55912da24630) lost focus even though it didn't have it
```
![1](https://user-images.githubusercontent.com/6218679/173883043-9006235a-6b1a-44ea-9eb1-f51e1ecb05d7.png)

![2](https://user-images.githubusercontent.com/6218679/173883006-6df63d06-08dc-43df-b9da-7d40af71114d.png)

**Comment by libreajans** [comment]
At first, I opened an issue to PoEdit and it's turned out a packaging error.

https://github.com/vslavik/poedit/issues/758

I use Ubuntu 22.04 with GNOME desktop. I also use breeze icon theme from KDE.

**Comment by libreajans** [comment]
I found out that it happens due to icon theme. I use Breeze icon theme from KDE. Error resolves when I change my icon theme to  another icon theme.

**Comment by haggen88** [comment]
same error -  Poedit 3.1 / Linux Mint 20.3  Cinnamon

![z1](https://user-images.githubusercontent.com/68134588/175831860-45ff1ad4-41cb-45e0-bdb7-8e35e17e350b.png)

![z2](https://user-images.githubusercontent.com/68134588/175831866-9416c55a-a845-4ffa-86fe-bffecab6363b.png)

terminal ouput:
> h2gn@h2gn:~$ flatpak run net.poedit.Poedit
Gtk-Message: 15:57:49.395: Failed to load module "xapp-gtk3-module"
Debug: Failed to connect to session manager: None of the authentication protocols specified are supported
./src/gtk/bitmap.cpp(937): assert ""IsOk()"" failed in GetWidth(): invalid bitmap
Debug: window wxTextCtrl(0x55f1773fa000) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x55f1773fa000) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x55f1773fa000) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x55f1773fa000) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x55f1773fa000) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x55f1773fa000) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x55f1773fa000) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x55f1773fa000) lost focus even though it didn't have it

>(net.poedit.Poedit:2): Gtk-CRITICAL **: 15:58:04.086: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
sh: line 1: addr2line: command not found
Debug: cannot read address information for stack frame #0
./src/gtk/bitmap.cpp(767): assert ""IsOk()"" failed in ConvertToImage(): invalid bitmap
./src/common/image.cpp(438): assert ""IsOk()"" failed in Scale(): invalid image
./src/gtk/bitmap.cpp(593): assert ""image.IsOk()"" failed in wxBitmap(): invalid image

**Comment by libreajans** [comment]
It's happening when you use non GTK icon themes.

haggen88 ***@***.***>, 26 Haz 2022 Paz, 23:14 tarihinde şunu
yazdı:
