### ISSUE TITLE
 org.gnome.Platform//42 is end-of-life

### ISSUE THREAD

**Issue by rusty-snake** [flathub/net.poedit.Poedit#40]
The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.

**Comment by haggen88** [comment]
ping @cho2, @TingPing , @bilelmoussaoui

**Comment by TingPing** [comment]
It seems non-trivial. See #39

**Comment by vslavik** [comment]
> It seems non-trivial. See https://github.com/flathub/net.poedit.Poedit/pull/39

Isn't `webkit2gtk-4.1` supposed to be API-compatible with 4.0? Then it should be rather trivial one-liner patch to wxWidgets' `configure.in` check, no?

**Comment by TingPing** [comment]
4.1 is API compatible but not ABI compatible.

All dependencies must be built against libsoup3 and not libsoup2.

Sometimes this is a simple rebuild sometimes not. I haven't looked into this specific project.

**Comment by hfiguiere** [comment]
> 4.1 is API compatible but not ABI compatible.

not exactly as it expose libsoup error codes, which wxWidgets, of course uses. I tried to build with 4.1 and it failed, instead I just built webkit.
